version: '3.0'

expectations:
  population_size: 1000000

actions:
  
  # generate metadata
  design:
    run: r:latest analysis/design.R
    outputs:
      moderately_sensitive:
        lib: analysis/lib/*

  # extract study population
  generate_study_population:
    run: cohortextractor:latest generate_cohort --output-format feather --study-definition study_definition
    needs: 
    - design
    outputs:
      highly_sensitive:
        cohort: output/extract/input.feather

  # generate custom dummy data
  generate_dummy_data:
    run: r:latest analysis/dummy_data.R
    needs:
    - design
    - generate_study_population
    outputs:
      highly_sensitive:
        dummydata: output/extract/dummy_data.feather
        
  process_extract:
    run: r:latest analysis/process_extract.R
    needs:
    - generate_study_population
    - generate_dummy_data
    outputs:
      highly_sensitive:
        data: output/extract/data_eligible.rds
      moderately_sensitive:
        skim: output/extract/skim_*.txt
        flowchart: output/extract/flowchart_*.csv
        